### PR TITLE
Read .ci.yml from workspace

### LINKED ISSUE #196: .ci.yml is pulled from source branch for pull requests rather than the "merged" branch
It looks like [the issue is here](https://github.com/groupon/DotCi/blob/master/src/main/java/com/groupon/jenkins/buildtype/dockercompose/DockerComposeBuild.java#L92) where `build.sha()` is the sha of the last commit on the source branch and not the "merged sha".  

The github api provides a [`merge_commit_sha`](https://developer.github.com/v3/pulls/#response-1), but it is deprecated. It may be simpler to just move the checkout to the first step in the DockerCompose build.

### PR DESCRIPTION
**Pull request by aheuermann**
Fixes #196 

I also removed the "build prs from same repository" property as discussed.

### CODE REVIEW

**Comment by suryagaddipati** [comment]
thanks @aheuermann . 

Also, checkout https://github.com/groupon/DotCi/commit/cf822113286aebaee3e2d32901d79218e8f26728 

You can now run  **any** plugin from .ci.yml

**Comment by suryagaddipati** [comment]
Released in `2.24.0`

**Comment by aheuermann** [comment]
:+1: on the plugin change

The update center is still showing `2.22.1` for me. Is there a lag between when it is submitted and when it shows up?

**Comment by suryagaddipati** [comment]
Looks like plugins require a wiki page to be specified in the pom. I just added it in `2.24.2` , hopefully it should show up in a couple of hrs. 

Meanwhile, maven repo for the releases is here http://maven.jenkins-ci.org:8081/content/repositories/releases/com/groupon/jenkins-ci/plugins/DotCi/

**Pull request merged**
