### PR TITLE
Using COMPOSE_PROJECT_NAME instead of passing -p argument

### LINKED ISSUE #187: Add COMPOSE_PROJECT_NAME environment variable for sub builds
We run some docker-compose services in our before script to migrate the database. Right now we have to run some logic ahead of time to get the [project name that dotci passes to it's docker-compose commands](https://github.com/groupon/DotCi/blob/master/src/main/java/com/groupon/jenkins/buildtype/dockercompose/BuildConfiguration.java#L60).
I think we could get rid of the need to determine the project name by using the `COMPOSE_PROJECT_NAME` environment variable rather than `-p` to make all compose commands for each sub build.  This way all compose calls (unless `-p` is explicitly specified) will run under the same project automatically.

### PR DESCRIPTION
**Pull request by aheuermann**
This fixes #187

### CODE REVIEW

**Comment by aheuermann** [comment]
We run `docker-compose run --rm` in the before so containers created by dotci are still named as expected for the plugins.  

Also, in case you hadn't seen it already, [compose added support for `docker-compose run --name container_name` in 1.5](https://github.com/docker/compose/pull/1930) which could make the plugin data extraction less fragile.

**Comment by suryagaddipati** [comment]
Thanks for the pr @aheuermann . I will review and merge it today at somepoint.

**Comment by vvitayau** [comment]
Using ``--name container_name`` is a bad idea if multiple DotCi builds are running on the same machine.

**Comment by vvitayau** [comment]
This is not an issue if docker slaves are not yet upgrade to ``docker-compose 1.5.0``
by merging https://github.com/groupon/DotCi/pull/173

**Comment by suryagaddipati** [comment]
hey @aheuermann looks like this won't work if multiple builds are running for the same project on the same slave machine ( multiple executors) as @vvitayau suggested. 

Are we understanding this correctly?

**Comment by aheuermann** [comment]
Sorry my comment was confusing. This PR does not add the `--name` argument or get rid of the compose project name. It is just changing the way the project name is passed to compose (using the [`COMPOSE_PROJECT_NAME` environment variable](https://docs.docker.com/compose/reference/overview/#compose-project-name) instead of the `-p` argument). [It includes job name and build number](https://github.com/groupon/DotCi/pull/188/files#diff-1def4d30908dec7a77c8eddd777d7853R46) so it will not conflict if multiple builds of the same type run on the same slave.

What this fixes is the need to guess the project name in the `before` script if you want to run compose commands for the project being used by the current dotci sub-build. [I created an example gist here](https://gist.github.com/aheuermann/1112e527a545a9e71216).

**Comment by aheuermann** [comment]
Regarding `--name`, I agree with @vvitayau. Project name is still needed (but it can be passed as `COMPOSE_PROJECT_NAME` env variable rather than `-p`) and name would need to be unique to the build like project name.

You could use `--name` with project name though to get rid of [this line](https://github.com/groupon/DotCi/blob/master/src/main/java/com/groupon/jenkins/buildtype/dockercompose/BuildConfiguration.java#L114) which assumes how compose will name the container.

```bash
#COMPOSE_PROJECT_NAME=orgprojectscriptnode8
#Project name env variable is set so no need to pass -p
containerName=${COMPOSE_PROJECT_NAME}_run
docker-compose --name $containerName $serviceName $command
....
export workingDir=`docker inspect -f '{{ .Config.WorkingDir }}' $containerName | sed -e 's|^/||g'`
```

The reason I brought this up is that if a user does a `docker-compose run` in the before with the same service name as the one specified in the dotci run and does not remove it prior to the dotci run, compose will name it `..._run_2` and it will not be picked up by the plugins.

**Comment by aheuermann** [comment]
@suryagaddipati @vvitayau have either of you had a chance to look at this?  Sorry to be a pest.

**Comment by suryagaddipati** [comment]
@aheuermann sorry I was out on vacation . I can get to it on monday.

**Comment by aheuermann** [comment]
@suryagaddipati @vvitayau I rebased my changes.

Let me know what you guys think about this. If you prefer to keep the `-p` I can update the `COMPOSE_PROJECT_NAME` to something like `DOTCI_COMPOSE_PROJECT_NAME` and pass that as the `-p` arguments. That would still allow me to run compose commands for the current project in the `before_each`.

**Comment by suryagaddipati** [comment]
hey @aheuermann sorry for late response. 

Ok so I ran this pr 

* on `master`
  
  ```
  docker-compose -f docker-compose.yml -p cisuryagaddipatidotci3 pull 
  docker-compose -f docker-compose.yml -p cisuryagaddipatidotci3 run -T ci echo meow
 ``` 


* on this PR 
  
  ```
  docker-compose -f docker-compose.yml  pull 
  docker-compose -f docker-compose.yml  run -T ci echo meow
 ``` 

notably project name is missing 

This wont work with multiple builds running on the same machine (with multiple executors) since name is defaulted to directory name ?

**Comment by suryagaddipati** [comment]
@aheuermann ahh..yea makes sense. I had no idea about env variables that can be passed for docker compose.

**Comment by suryagaddipati** [comment]
Thanks for the PR. I appreciate your contributions @aheuermann

**Comment by suryagaddipati** [comment]
released in `2.22.0`

**Comment by aheuermann** [comment]
Great, thanks for taking a look at this and also for the quick fix on #193

**Pull request merged**
